import 'package:flutter/material.dart';

myText(
  String? label, {
  TextStyle? textStyle,
  double? height,
  double? width,
  EdgeInsets? padding,
  EdgeInsets? margin,
  List<Shadow>? shadows,
  AlignmentGeometry alignment = Alignment.center,
  Color? background,
  Color? selectionColor = Colors.indigo,
  Decoration? decoration,
  int? maxLines,
  int? minLines,
  double? fontsize,
  String? fontFamily = 'RobotoSlab',
  Color? color,
  FontStyle? fontStyle = FontStyle.normal,
  double? textHeight,
  double? textScaleFactor,
  double? letterSpacing,
  double? wordSpacing,
  TextAlign? textAlign,
  FontWeight? fontWeight = FontWeight.normal,
}) =>
    Container(
        height: height,
        width: width,
        padding: padding,
        alignment: alignment,
        clipBehavior: Clip.none,
        color: background,
        decoration: decoration,
        margin: margin,
        child: Text(label ?? '',
            overflow: TextOverflow.ellipsis,
            maxLines: maxLines,
            textAlign: textAlign,
            textScaleFactor: textScaleFactor,
            selectionColor: selectionColor,
            style: (textStyle != null)
                ? textStyle
                : TextStyle(
                    shadows: shadows,
                    fontSize: fontsize,
                    fontFamily: fontFamily,
                    color: color,
                    fontStyle: fontStyle,
                    height: textHeight,
                    letterSpacing: letterSpacing,
                    wordSpacing: wordSpacing,
                    fontWeight: fontWeight)));

// myAutoSizeText({
//   required String? label,
//   TextStyle? style,
//   double? height,
//   double? width,
//   String? fontFamily = 'RobotoSlab',
//   int maxLines = 1,
//   int minLines = 1,
//   double? textScaleFactor,
//   double fontsize = 10,
//   double maxFontsize = 20,
//   double minFontsize = 10,
//   double? textHeight,
//   double? letterSpacing,
//   double? wordSpacing,
//   TextAlign? textAlign,
//   FontStyle? fontStyle = FontStyle.normal,
//   FontWeight fontWeight = FontWeight.w500,
//   EdgeInsets padding = const EdgeInsets.all(0),
//   EdgeInsets? margin,
//   AlignmentGeometry alignment = Alignment.center,
//   Color? color,
//   Color? background,
//   double borderRadius = 6,
// }) =>
//     Container(
//         height: height,
//         width: width,
//         padding: padding,
//         margin: margin,
//         alignment: alignment,
//         decoration: BoxDecoration(color: background, borderRadius: BorderRadius.circular(borderRadius)),
//         child: AutoSizeText(label ?? '',
//             maxFontSize: maxFontsize,
//             minFontSize: minFontsize,
//             stepGranularity: 1,
//             overflow: TextOverflow.ellipsis,
//             maxLines: maxLines,
//             textAlign: textAlign,
//             textScaleFactor: textScaleFactor,
//             style: (style != null)
//                 ? style
//                 : TextStyle(
//                     fontFamily: fontFamily,
//                     color: color,
//                     fontStyle: fontStyle,
//                     height: textHeight,
//                     letterSpacing: letterSpacing,
//                     wordSpacing: wordSpacing,
//                     fontSize: fontsize,
//                     fontWeight: fontWeight)));
