// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class FirebaseConnection {
  static DatabaseReference connect = FirebaseDatabase.instance.ref('portfolio');
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTkTT4F9-ej3jjIhubHRkLImrtAH7Vlc',
    appId: '1:1030284041228:web:21eb0692124fdd0d486229',
    messagingSenderId: '1030284041228',
    projectId: 'portfolio-d35f0',
    authDomain: 'portfolio-d35f0.firebaseapp.com',
    databaseURL: 'https://portfolio-d35f0-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d35f0.appspot.com',
    measurementId: 'G-CTZ280704E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yVe1wD6pUAfYGzawrhRXRaH303Oxxp4',
    appId: '1:1030284041228:android:367ff2677a390442486229',
    messagingSenderId: '1030284041228',
    projectId: 'portfolio-d35f0',
    databaseURL: 'https://portfolio-d35f0-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d35f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2chRdgAdpfQnsueAiCN4KW4bfrAaSBOA',
    appId: '1:1030284041228:ios:28e8196fc6b9b2e1486229',
    messagingSenderId: '1030284041228',
    projectId: 'portfolio-d35f0',
    databaseURL: 'https://portfolio-d35f0-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d35f0.appspot.com',
    iosClientId: '1030284041228-unv7pquktli70s5jl8j3orck16n250q2.apps.googleusercontent.com',
    iosBundleId: 'com.akaomarfahim.portfolio.portfolioFinalOmar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2chRdgAdpfQnsueAiCN4KW4bfrAaSBOA',
    appId: '1:1030284041228:ios:28e8196fc6b9b2e1486229',
    messagingSenderId: '1030284041228',
    projectId: 'portfolio-d35f0',
    databaseURL: 'https://portfolio-d35f0-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d35f0.appspot.com',
    iosClientId: '1030284041228-unv7pquktli70s5jl8j3orck16n250q2.apps.googleusercontent.com',
    iosBundleId: 'com.akaomarfahim.portfolio.portfolioFinalOmar',
  );
}
